### ISSUE TITLE
changing between edit and preview mode appends to the bottom of the recipe

### ISSUE THREAD

**Issue by neongrey** [rveciana/obsidian-cooklang#2]
if I open up the recipe file, it opens in preview mode, which is fine.

I then change to edit mode, causing the original markup to display beneath the preview. The preview remains visible.

If i change back to preview mode from edit, the preview version is appended to the bottom of the file. Going back to edit from there will append the markup to below the second preview. Going into preview again will append another preview and so on.

Going into a different file and then coming back into the recipe does reset the display.

I've included a gif showing what's going on. Thanks!!

![appending preview etc](https://github.com/rveciana/obsidian-cooklang/assets/17973965/44ee581e-92f7-4f7d-883a-e966b34f9c26)

**Comment by rveciana** [comment]
I'll take a look. This didn't happen before, and it's also happening now in my computer. Maybe a new obsidian version?

**Comment by neongrey** [comment]
I think one did come out a few days ago. Thanks for checking!

**Comment by rveciana** [comment]
I fixed it (it works on my computer!) on version 0.0.9. Please tell me in case it's not working.

**Comment by rveciana** [comment]
fixed

**Comment by neongrey** [comment]
yes, looks great now, thanks so much and for the fraction toggle, also!
