### ISSUE TITLE
Comments aren't recognised or formatted

### ISSUE THREAD

**Issue by lyndaljane** [rveciana/obsidian-cooklang#3]
First: thank you for picking this up! The original was good but it's broken now, so glad there's an alternative.

I did notice that [comments](https://cooklang.org/docs/spec/#comments) formatted to Cooklang specs are either hidden in reading mode, or are parsed as cooking steps.

Comments added with "--" between the instruction and the comment, or block comments on a single line with "[-" and "-]" at the start and end are not visible in Reading view.

Block comments split over multi lines display in Reading mode with the first line appended to the end of the last Step, and subsequent lines are parsed as Steps too. In my file I had a single-line block comment between Step 8 and a multi-line block comment; the Reading mode dropped the single-line block comment and chucked the first line of the multi-line at the end of Step 8.

Usages for comments are Descriptions, or Cooking Notes that aren't part of the general recipe method flow (like, "If you use fridge cold eggs, you will notice the batter is thicker. It will still work just fine, but room temperature eggs is better – it makes the batter pourable into the pan. Cake may also need an extra 5 minutes in the oven.").

**Comment by rveciana** [comment]
Hi! Thanks for the issue. I think that the comments aren't supposed to be rendered. I try this "recipe" on the sandbox and don't see the comment https://biowaffeln.github.io/cooklang-parser/

```
-- Don't burn the roux!

Mash @potato{2%kg} until smooth -- alternatively, boil 'em first, then mash 'em, then stick 'em in a stew.
```

Do you have any rendering example? Maybe I could add an icon to indicate that there's a comment or something (or an option on settings to show them)...

![imatge](https://github.com/user-attachments/assets/d555bfab-7699-416d-a1d6-7cb6cbcd8dd3)

**Comment by rveciana** [comment]
Thanks for the issue! I'll try to reproduce it first and then fix it. It seems a parser problem, but let me check.

**Comment by rveciana** [comment]
As you can see, it's the parser that doesn't interpret the multiline comments properly. I'll try to do a PR there, although I see that the last commit was 9 months ago...

![imatge](https://github.com/user-attachments/assets/bbaf2582-fffb-4072-8336-a5d16b0ad40f)

**Comment by rveciana** [comment]
OK, so the PR is here: https://github.com/cooklang/cooklang-ts/pull/25
When it's accepted, I'll update the version I'm using so it works. I hope it's accepted some time soon...

**Comment by rveciana** [comment]
Done! You can try version 0.0.12 now
